user www-data;
worker_processes auto;
error_log /dev/stderr warn;
pid /run/nginx.pid;
events { worker_connections 1024; }
http {
  include /etc/nginx/mime.types;
  access_log /dev/stdout;
  server_tokens off;
  server {
    listen __PORT__;
    root /var/www/html/public;
    index index.php;
    client_max_body_size 1m;
    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options DENY always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;
    location / { try_files $uri $uri/ /index.php?$query_string; }
    location ~ ^/index\.php$ {
      include fastcgi_params;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      fastcgi_param HTTP_PROXY "";
      fastcgi_pass 127.0.0.1:9000;
    }
    location ~ \.php$ { return 404; }
    location ~ /\. { deny all; }
  }
}
